# Session is the type of the database handle every function here receives.
# It is passed in by the controller rather than created here, so that several
# calls can share one session and be committed together as a single unit.
from sqlalchemy.orm import Session

# Import the account classes from their new location in app/models.
from app.models.account import Account, SavingsAccount, CheckingAccount


# Function that creates a new account and saves it to the accounts table.
# db is the database session.
# owner is the account holder's name.
# owner_id links this account back to the Customer that owns it.
# account_type is either "Savings" or "Checking".
# balance is the starting balance, defaults to 0.
# branch_code is the branch this account belongs to. It defaults to None so
# accounts can still be opened without one, but an account needs a branch
# before it can show up in filter_accounts() below.
def create_account(
    db: Session,
    owner: str,
    owner_id: int,
    account_type: str,
    balance: float = 0,
    branch_code: int = None,
):
    # Pick which class to instantiate based on the requested account_type.
    # Which class we pick is also what fills in the "type" column, because
    # each subclass declares its own polymorphic_identity.
    if account_type.lower() == "savings":
        new_account = SavingsAccount(owner, owner_id, balance)
    elif account_type.lower() == "checking":
        new_account = CheckingAccount(owner, owner_id, balance)
    else:
        # Return None so the controller knows the request was invalid.
        return None

    new_account.branch_code = branch_code

    # add() stages the object, commit() writes it and ends the transaction.
    db.add(new_account)
    db.commit()

    # The id and account_number were both generated by PostgreSQL during the
    # commit, so we have to ask for the row again to see them. refresh()
    # re-reads this one object.
    db.refresh(new_account)

    return new_account


# Returns every account that belongs to the given branch AND holds at least
# min_balance. Both conditions have to be true for an account to be included.
# branch_code is the branch we are filtering on.
# min_balance is the smallest balance an account can have and still match.
def filter_accounts(db: Session, branch_code: int, min_balance: float):
    # Two filter() calls chained together means AND, which is the same
    # behaviour the original loop had when it skipped non-matching accounts.
    # The comparison runs inside PostgreSQL, so only matching rows come back.
    return (
        db.query(Account)
        .filter(Account.branch_code == branch_code)
        .filter(Account._balance >= min_balance)
        .all()
    )


# Finds a single account by its id.
# Returns None when there is no account with that id, so callers can decide
# how to report it.
def get_account(db: Session, account_id: int):
    return db.query(Account).filter(Account.account_number == account_id).first()


# Same lookup as get_account, but locks the row until the current
# transaction finishes.
#
# with_for_update() issues SELECT ... FOR UPDATE. If two transfers touch the
# same account at the same moment, the second one waits at this line until
# the first has committed, so it reads the already-updated balance instead
# of a stale one. That is what stops two simultaneous withdrawals from both
# passing the "enough money?" check and overdrawing the account.
def get_account_for_update(db: Session, account_id: int):
    return (
        db.query(Account)
        .filter(Account.account_number == account_id)
        .with_for_update()
        .first()
    )