"""updated primary key for branch table

Revision ID: 05f2e5c4aef3
Revises: 76e20500de2e
Create Date: 2026-08-11 14:16:35.167423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f2e5c4aef3'
down_revision: Union[str, Sequence[str], None] = '76e20500de2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'accounts', 'branches', ['branch_id'], ['branch_code'])
    op.create_foreign_key(None, 'customers', 'branches', ['branch_id'], ['branch_code'])
    op.create_foreign_key(None, 'staff', 'branches', ['branch_id'], ['branch_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    # ### end Alembic commands ###
