"""add users table

Revision ID: 38d903c71643
Revises: 82023a888c6a
Create Date: 2026-08-11 16:01:20.708929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d903c71643'
down_revision: Union[str, Sequence[str], None] = '82023a888c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'id')
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_id'], ['account_number'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['from_account_id'], ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.add_column('accounts', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
