"""initial schema

Revision ID: 426f100f79f6
Revises: 
Create Date: 2026-08-11 11:20:33.756874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426f100f79f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

account_number_seq = sa.Sequence("account_number_seq", start=1000)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    # sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('manager_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('branch_code'),
    sa.UniqueConstraint('branch_code')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    # Named branch_code, not branch_id, to match Customer.branch_code. The
    # column holds the branch's code, which is the branches table's primary
    # key, so calling it an id never lined up with what it stores.
    sa.Column('branch_code', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_code'], ['branches.branch_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('branch_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_code'], ['branches.branch_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.execute(sa.schema.CreateSequence(account_number_seq))
    op.create_table('accounts',
    sa.Column('account_number', sa.Integer(), server_default=account_number_seq.next_value(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('branch_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_code'], ['branches.branch_code'], ),
    # owner_id is the link back to the customer who owns the account. There
    # was a second customer_id column pointing at the same table, which no
    # model ever declared.
    sa.ForeignKeyConstraint(['owner_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('account_number')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=True),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.account_number'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.account_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    # A bcrypt hash is 60 characters. The column was 20, which silently made
    # every stored hash unusable. 255 leaves room for a longer algorithm later.
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('sub', sa.String(length=40), nullable=False),
    # nullable=False to match User.roles. A user with no role would pass
    # authentication and then match none of the authorisation rules.
    sa.Column('roles', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    # Two accounts must not share an identity. sub is what lands in the
    # token's subject claim, so a duplicate would make two users
    # indistinguishable to every route that reads it.
    sa.UniqueConstraint('sub'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('staff')
    op.drop_table('customers')
    op.drop_table('branches')
    op.execute(sa.schema.DropSequence(account_number_seq))
    # ### end Alembic commands ###
